/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    '/about/': RouteRecordInfo<'/about/', '/about', Record<never, never>, Record<never, never>>,
    '/about/site': RouteRecordInfo<'/about/site', '/about/site', Record<never, never>, Record<never, never>>,
    '/archives/': RouteRecordInfo<'/archives/', '/archives', Record<never, never>, Record<never, never>>,
    '/categories/': RouteRecordInfo<'/categories/', '/categories', Record<never, never>, Record<never, never>>,
    '/girls/': RouteRecordInfo<'/girls/', '/girls', Record<never, never>, Record<never, never>>,
    '/links/': RouteRecordInfo<'/links/', '/links', Record<never, never>, Record<never, never>>,
    '/page/[page]': RouteRecordInfo<'/page/[page]', '/page/:page', { page: ParamValue<true> }, { page: ParamValue<false> }>,
    '/posts/20240728 建站说明': RouteRecordInfo<'/posts/20240728 建站说明', '/posts/20240728 建站说明', Record<never, never>, Record<never, never>>,
    '/posts/静态代码分析/20240729 1 静态分析概述/20240729 1 静态分析概述': RouteRecordInfo<'/posts/静态代码分析/20240729 1 静态分析概述/20240729 1 静态分析概述', '/posts/静态代码分析/20240729 1 静态分析概述/20240729 1 静态分析概述', Record<never, never>, Record<never, never>>,
    '/posts/静态代码分析/20240730 2 程序的中间表示/20240730 2 程序的中间表示': RouteRecordInfo<'/posts/静态代码分析/20240730 2 程序的中间表示/20240730 2 程序的中间表示', '/posts/静态代码分析/20240730 2 程序的中间表示/20240730 2 程序的中间表示', Record<never, never>, Record<never, never>>,
    '/posts/静态代码分析/20240731 3 数据流分析-应用/20240731 3 数据流分析-应用': RouteRecordInfo<'/posts/静态代码分析/20240731 3 数据流分析-应用/20240731 3 数据流分析-应用', '/posts/静态代码分析/20240731 3 数据流分析-应用/20240731 3 数据流分析-应用', Record<never, never>, Record<never, never>>,
    '/posts/静态代码分析/20240801 4 数据流分析-基础/20240801 4 数据流分析-基础': RouteRecordInfo<'/posts/静态代码分析/20240801 4 数据流分析-基础/20240801 4 数据流分析-基础', '/posts/静态代码分析/20240801 4 数据流分析-基础/20240801 4 数据流分析-基础', Record<never, never>, Record<never, never>>,
    '/posts/静态代码分析/20240802 5 过程间分析/20240802 5 过程间分析': RouteRecordInfo<'/posts/静态代码分析/20240802 5 过程间分析/20240802 5 过程间分析', '/posts/静态代码分析/20240802 5 过程间分析/20240802 5 过程间分析', Record<never, never>, Record<never, never>>,
    '/posts/静态代码分析/20240803 6 指针分析-引入/20240803 6 指针分析-引入': RouteRecordInfo<'/posts/静态代码分析/20240803 6 指针分析-引入/20240803 6 指针分析-引入', '/posts/静态代码分析/20240803 6 指针分析-引入/20240803 6 指针分析-引入', Record<never, never>, Record<never, never>>,
    '/posts/静态代码分析/20240804 7 指针分析-基础/20240804 7 指针分析-基础': RouteRecordInfo<'/posts/静态代码分析/20240804 7 指针分析-基础/20240804 7 指针分析-基础', '/posts/静态代码分析/20240804 7 指针分析-基础/20240804 7 指针分析-基础', Record<never, never>, Record<never, never>>,
    '/posts/静态代码分析/20240805 8 指针分析-上下文敏感/20240805 8 指针分析-上下文敏感': RouteRecordInfo<'/posts/静态代码分析/20240805 8 指针分析-上下文敏感/20240805 8 指针分析-上下文敏感', '/posts/静态代码分析/20240805 8 指针分析-上下文敏感/20240805 8 指针分析-上下文敏感', Record<never, never>, Record<never, never>>,
    '/posts/静态代码分析/20240806 9 静态分析与安全/20240806 9 静态分析与安全': RouteRecordInfo<'/posts/静态代码分析/20240806 9 静态分析与安全/20240806 9 静态分析与安全', '/posts/静态代码分析/20240806 9 静态分析与安全/20240806 9 静态分析与安全', Record<never, never>, Record<never, never>>,
    '/posts/静态代码分析/20240807 10 基于 Datalog 的程序分析/20240807 10 基于 Datalog 的程序分析': RouteRecordInfo<'/posts/静态代码分析/20240807 10 基于 Datalog 的程序分析/20240807 10 基于 Datalog 的程序分析', '/posts/静态代码分析/20240807 10 基于 Datalog 的程序分析/20240807 10 基于 Datalog 的程序分析', Record<never, never>, Record<never, never>>,
    '/posts/静态代码分析/20240809 11 CFL 可达与 IFDS/20240809 11 CFL 可达与 IFDS': RouteRecordInfo<'/posts/静态代码分析/20240809 11 CFL 可达与 IFDS/20240809 11 CFL 可达与 IFDS', '/posts/静态代码分析/20240809 11 CFL 可达与 IFDS/20240809 11 CFL 可达与 IFDS', Record<never, never>, Record<never, never>>,
    '/posts/静态代码分析/20240810 12 完全性与近似完全性/20240810 12 完全性与近似完全性': RouteRecordInfo<'/posts/静态代码分析/20240810 12 完全性与近似完全性/20240810 12 完全性与近似完全性', '/posts/静态代码分析/20240810 12 完全性与近似完全性/20240810 12 完全性与近似完全性', Record<never, never>, Record<never, never>>,
    '/posts/区块链基础/20240801 geth 基础': RouteRecordInfo<'/posts/区块链基础/20240801 geth 基础', '/posts/区块链基础/20240801 geth 基础', Record<never, never>, Record<never, never>>,
    '/tags/': RouteRecordInfo<'/tags/', '/tags', Record<never, never>, Record<never, never>>,
  }
}
